#!/bin/bash
cd Desktop
echo Linux install script version 1.1
echo by Pinakin Kale
echo starting up
echo .
echo ..
echo ...
echo starting
echo Updating Everything!
sudo apt update
sudo apt full-upgrade -y
#Apt Installs
sudo apt-get install htop -y
sudo apt-get openssh-server -y
sudo apt install xrdp xorgxrdp -y
sudo apt-get install audacity -y
sudo apt-get install psensor -y
sudo apt-get alsa -y 
sudo install unity-tweak-tool -y
sudo apt install filezilla -y
sudo apt install apache2 -y
sudo apt install net-tools -y
sudo apt install libreoffice -y
sudo apt install vlc -y
sudo apt install audacity -y
#snap installs
sudo snap install spotify 
sudo snap install code --classic
#Second Upgrade
echo Hold on a sec
sudo apt update
sudo apt full-upgrade -y
echo Cleaning up!
sudo apt autoremove -y
sudo apt autoclean -y
echo ########################
echo almost done
echo ########################
sudo apt install sl -y
sudo apt install sysvbanner -y
echo Now watch this cool train
sl
clear 
Banner Done!
echo Made by Pinakin Kale 2020


#Made By Pinakin Kale 7/20/20. For Ubuntu Based installs only